// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeJro2wEDFodZcs1Jw1I-PWaxvB22T2-M',
    appId: '1:772143071518:android:2b4100e7fa24db0a5cc90f',
    messagingSenderId: '772143071518',
    projectId: 'ensena-capstone-grupo3',
    storageBucket: 'ensena-capstone-grupo3.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxPQ-qd8Et10UyvosTQb3WEZfG7QhvyV0',
    appId: '1:772143071518:web:7e23bafc7a933ee55cc90f',
    messagingSenderId: '772143071518',
    projectId: 'ensena-capstone-grupo3',
    authDomain: 'ensena-capstone-grupo3.firebaseapp.com',
    storageBucket: 'ensena-capstone-grupo3.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuxHnTnqN6UYRX8UMZraAZnvAsSfeAzE8',
    appId: '1:772143071518:ios:bbdda26e725e05075cc90f',
    messagingSenderId: '772143071518',
    projectId: 'ensena-capstone-grupo3',
    storageBucket: 'ensena-capstone-grupo3.appspot.com',
    iosBundleId: 'com.example.ensenaGrupo3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuxHnTnqN6UYRX8UMZraAZnvAsSfeAzE8',
    appId: '1:772143071518:ios:6e114bedc57df67c5cc90f',
    messagingSenderId: '772143071518',
    projectId: 'ensena-capstone-grupo3',
    storageBucket: 'ensena-capstone-grupo3.appspot.com',
    iosBundleId: 'com.grupo3.ensena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxPQ-qd8Et10UyvosTQb3WEZfG7QhvyV0',
    appId: '1:772143071518:web:1c4d0733fb1b0f575cc90f',
    messagingSenderId: '772143071518',
    projectId: 'ensena-capstone-grupo3',
    authDomain: 'ensena-capstone-grupo3.firebaseapp.com',
    storageBucket: 'ensena-capstone-grupo3.appspot.com',
  );

}